version: '3.6'
services:
  intel:
    restart: always
    container_name: intel
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '9193:9193'
    environment:
      - VIRTUAL_HOST=intel.shuttlers.africa
      - LETSENCRYPT_HOST=intel.shuttlers.africa
      - GIN_MODE=release