version: '3.6'
services:
  intel:
    restart: always
    container_name: intel
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '127.0.0.1:9193:9193'
    environment:
      - VIRTUAL_HOST=intel.shuttlers.africa
      - LETSENCRYPT_HOST=intel.shuttlers.africa
      - MONGO_URI=mongodb://mongo:27017
      - CONN_STR=mongodb://mongo:27017   
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongo
    volumes:
      - .:/src
      - .:/var/www

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '127.0.0.1:27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      VIRTUAL_HOST: "mongodb://mongo:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '127.0.0.1:8089:8089'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017/"
      VIRTUAL_HOST: mongo-express.shuttlers.africa
    depends_on:
      - mongo  

volumes:
  mongodb_data_cont: