version: '3.6'
services: 
  intel: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9193:9193"
    environment:
      - VIRTUAL_HOST=intel.shuttlers.africa
      - LETSENCRYPT_HOST=intel.shuttlers.africa
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - node-network
  
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - /home/oluwaseyi_yusuf/inteldb/mongo:/data/db
    networks:
      - node-network
    
volumes:
  mongo:

networks:
  node-network:
    driver: bridge