version: '3.6'
services:
  intel:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9193:9193"
    environment:
      - VIRTUAL_HOST=intel.shuttlers.africa
      - LETSENCRYPT_HOST=intel.shuttlers.africa
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - intel-network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - /intel/bin/mongo:/data/db
    networks:
      - intel-network

volumes:
  mongo:

networks:
  intel-network:
    driver: bridge